name: newbkmmobile
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI & dasar
  cupertino_icons: ^1.0.8
  carousel_slider: ^5.1.1
  photo_view: ^0.15.0
  image_picker: ^1.1.2
  intl: ^0.20.2

  # State management
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  rxdart: ^0.28.0

  # Local storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.3.2
  path_provider: ^2.1.4

  # Network
  http: ^1.2.2
  flutter_plugin_android_lifecycle: ^2.0.22

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Lint & code generation
  flutter_lints: ^6.0.0
  build_runner: ^2.4.6
  hive_generator: ^2.0.0

  # Tools tambahan
  flutter_launcher_icons: ^0.14.4
  mockito: ^5.4.4
  http_mock_adapter: ^0.6.1
  hive_test: ^1.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/BKM_Logo_BG_White.png"
  adaptive_icon_background: "assets/BKM_Logo_BG_White.png"
  adaptive_icon_foreground: "assets/BKM_Logo_BG_White.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/
